CREATE DATABASE crispet;

USE crispet;

CREATE TABLE usuarios(

id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100),
email VARCHAR(100) UNIQUE,
senha VARCHAR(255)

);

CREATE TABLE contatos(

id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100),
email VARCHAR(100),
telefone VARCHAR(20),
assunto VARCHAR(100),
mensagem TEXT,
data_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE pets(

id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100),
raca VARCHAR(100),
descricao TEXT,
cidade VARCHAR(100),
imagem VARCHAR(255),
status_pet VARCHAR(50),
data_postagem TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

-- ADMIN

INSERT INTO usuarios
(nome,email,senha)

VALUES

(
'Administrador',
'admin@crispet.com',
'$2y$10$4lQY3P8RmR6h0hSPQxMZ8O6j7L0mJkXrL4aA0I8zvL8f0N0Xx1h3K'
);

-- SENHA = 123456